# Generated by Django 4.2.27 on 2026-01-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias Bancario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cbu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CBU/CVU'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(blank=True, help_text='Ej: Ferretería, Combustible', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='beneficio_detalle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='beneficio_organismo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
