# Generated by Django 5.2.8 on 2025-11-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='grupo',
            field=models.CharField(choices=[('VEHICULOS', 'Vehículos'), ('INSUMOS', 'Insumos generales'), ('CONSTRUCCION', 'Construcción / Obra'), ('AYUDAS', 'Ayudas sociales'), ('OTROS', 'Otros')], default='OTROS', help_text='Sirve para agrupar gastos en vistas (vehículos, insumos, construcción, ayudas, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='beneficiario_dni',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI beneficiario'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='beneficiario_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre beneficiario'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuenta_destino_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cuenta destino'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuenta_origen_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cuenta origen'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='programa_ayuda_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Programa de ayuda'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='proveedor_cuit',
            field=models.CharField(blank=True, max_length=20, verbose_name='CUIT proveedor'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='proveedor_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre proveedor'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='vehiculo_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='es_ayuda_social',
            field=models.BooleanField(default=False, help_text='Marca si esta categoría corresponde a ayudas sociales.'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='es_combustible',
            field=models.BooleanField(default=False, help_text='Marca si esta categoría es de combustible.'),
        ),
    ]
