# Generated by Django 4.2.27 on 2026-01-22 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_proveedor_alias_proveedor_cbu_proveedor_rubro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traslado',
            options={'ordering': ['id'], 'verbose_name': 'Traslado', 'verbose_name_plural': 'Traslados'},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='hoja_ruta',
            field=models.ForeignKey(blank=True, help_text='Si corresponde, imputar este movimiento a una Hoja de Ruta (día/turno).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.hojaruta'),
        ),
    ]
