# Generated by Django 5.2.8 on 2025-11-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_categoria_grupo_movimiento_beneficiario_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='detalle_servicios',
            field=models.CharField(blank=True, help_text='Detalle del servicio (N° conexión, lote, referencia de pago, etc.).', max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='paga_servicios',
            field=models.BooleanField(default=False, help_text='Indica si esta persona paga servicios a la comuna (agua, tasas, etc.).'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='es_servicio',
            field=models.BooleanField(default=False, help_text='Marca si esta categoría corresponde a cobro de servicios municipales (agua, tasas, etc.).'),
        ),
    ]
