# Generated by Django 4.2.27 on 2026-01-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_traslado_options_movimiento_hoja_ruta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-id'], 'verbose_name': 'Orden de compra', 'verbose_name_plural': 'Órdenes de compra'},
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='rubro_principal',
            field=models.CharField(blank=True, choices=[('AS', 'Ayudas Sociales'), ('CB', 'Combustible'), ('OB', 'Obras y Materiales'), ('SV', 'Servicios'), ('PE', 'Personal / Jornales'), ('HI', 'Herramientas e Insumos'), ('OT', 'Otros / General')], default='OT', max_length=2),
        ),
    ]
