# Generated by Django 5.2.8 on 2025-11-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_beneficiario_detalle_servicios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='sector_laboral',
            field=models.ForeignKey(blank=True, help_text='Área o sector en el que trabaja para la comuna (si corresponde).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiarios_laborales', to='finanzas.area'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='tipo_vinculo',
            field=models.CharField(choices=[('NINGUNO', 'Sin vínculo laboral'), ('PLANTA', 'Planta permanente'), ('JORNAL', 'Jornalizado'), ('EVENTUAL', 'Eventual / changuista'), ('HONORARIO', 'Honorarios / contratad@')], default='NINGUNO', help_text='Vínculo laboral con la comuna (planta, jornal, eventual, honorarios).', max_length=20),
        ),
        migrations.AddField(
            model_name='categoria',
            name='es_personal',
            field=models.BooleanField(default=False, help_text='Marca si esta categoría corresponde a sueldos, jornales u otros gastos de personal.'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='es_ayuda_social',
            field=models.BooleanField(default=False, help_text='Marca si esta categoría corresponde a ayudas sociales a personas u hogares.'),
        ),
    ]
