# Generated by Django 5.2.8 on 2025-11-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_beneficiario_sector_laboral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='tipo_pago_persona',
            field=models.CharField(choices=[('NINGUNO', 'Ninguno / genérico'), ('SUELDO', 'Pago de sueldo (planta permanente)'), ('CHANGA', 'Pago de changa / jornal / eventual')], default='NINGUNO', help_text="Si el movimiento está vinculado a una persona, indicá si es sueldo de planta permanente o pago de changa/jornal. Dejá 'Ninguno' para ayudas sociales u otros casos.", max_length=20),
        ),
    ]
