# Generated by Django 4.2.27 on 2026-01-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_ordencompra_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViajeVehiculo',
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['activo', 'patente'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='destino',
            field=models.CharField(blank=True, help_text='Destino principal o zona', max_length=200),
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='km_recorridos',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='chasis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='motor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('CAMIONETA', 'Camioneta / Utilitario'), ('CAMION', 'Camión'), ('MAQUINARIA', 'Maquinaria Pesada'), ('AUTO', 'Automóvil'), ('OTRO', 'Otro')], default='CAMIONETA', max_length=20),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='chofer_nombre',
            field=models.CharField(blank=True, help_text='Nombre de respaldo', max_length=150),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='odometro_fin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='odometro_inicio',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='origen',
            field=models.CharField(default='Base / Localidad', max_length=150),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='otros_pasajeros',
            field=models.CharField(blank=True, help_text='Nombres de no empadronados', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(help_text='Nombre interno (ej: Móvil 1)', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='horometro_referencia',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje_referencia',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(help_text='Dominio sin espacios', max_length=20, unique=True),
        ),
    ]
