# Generated by Django 5.2.8 on 2025-11-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_movimiento_tipo_pago_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='beneficio_detalle',
            field=models.CharField(blank=True, help_text='Ej: AUH, Pensión no contributiva, Jubilación mínima, Potenciar Trabajo, Tarjeta Alimentar, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='beneficio_monto_aprox',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto aproximado mensual (si se conoce).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='beneficio_organismo',
            field=models.CharField(blank=True, help_text='Organismo que lo otorga. Ej: ANSES, Provincia, Comuna, ONG, etc.', max_length=120),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='percibe_beneficio',
            field=models.BooleanField(default=False, help_text='Indica si percibe pensión o algún beneficio social (AUH, PNC, jubilación, etc.).'),
        ),
    ]
