# Generated by Django 4.2.27 on 2026-01-27 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0005_delete_viajevehiculo_alter_vehiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjuntoordentrabajo',
            options={'verbose_name': 'Adjunto de OT', 'verbose_name_plural': 'Adjuntos'},
        ),
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-id'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AlterModelOptions(
            name='ordentrabajomaterial',
            options={'verbose_name': 'Material de OT', 'verbose_name_plural': 'Materiales de OT'},
        ),
        migrations.RenameField(
            model_name='adjuntoordentrabajo',
            old_name='orden_trabajo',
            new_name='orden',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='categoria_ingreso',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='importe_estimado',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='importe_final',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='movimiento_ingreso',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='ordentrabajomaterial',
            name='costo_total',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalización Real'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Real'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='observaciones_internas',
            field=models.TextField(blank=True, verbose_name='Notas Privadas'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título Corto'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Lugar / Dirección'),
        ),
        migrations.AlterField(
            model_name='adjuntoordentrabajo',
            name='archivo',
            field=models.FileField(upload_to='ots_docs/%Y/%m/', verbose_name='Foto / Documento'),
        ),
        migrations.AlterField(
            model_name='adjuntoordentrabajo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adjuntoordentrabajo',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador (Pendiente)'), ('EN_PROCESO', 'En Ejecución'), ('FINALIZADA', 'Finalizada (Técnica)'), ('ENTREGADA', 'Entregada / Certificada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_ot',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='numero',
            field=models.CharField(blank=True, db_index=True, help_text='Se genera automático (Ej: OT-2026-005)', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente'), ('CRITICA', 'Crítica (Emergencia)')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_asignadas', to='finanzas.beneficiario'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='responsable_texto',
            field=models.CharField(blank=True, help_text='Capataz o encargado', max_length=200),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_solicitadas', to='finanzas.beneficiario'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='solicitante_texto',
            field=models.CharField(blank=True, help_text='Nombre snapshot o externo', max_length=200),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tipo_trabajo',
            field=models.CharField(blank=True, help_text='Ej: Electricidad, Albañilería', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='trabajos_realizados',
            field=models.TextField(blank=True, verbose_name='Informe Técnico Final'),
        ),
        migrations.AlterField(
            model_name='ordentrabajomaterial',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordentrabajomaterial',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='ordentrabajomaterial',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Material / Insumo'),
        ),
        migrations.AlterField(
            model_name='ordentrabajomaterial',
            name='unidad',
            field=models.CharField(default='Unidad', help_text='Mts, Kg, Lts, Cajas', max_length=20),
        ),
    ]
