# Generated by Django 5.2.8 on 2025-11-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_beneficiario_beneficio_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='condicion_pago',
            field=models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('30', '30 días'), ('60', '60 días'), ('OTRO', 'Otro plazo')], max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='factura_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='factura_numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='factura_tipo',
            field=models.CharField(blank=True, choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C'), ('X', 'Factura X / Ticket'), ('OTRO', 'Otro comprobante')], max_length=10),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro medio')], max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='orden_pago_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='orden_pago_observaciones',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
