# Generated by Django 4.2.27 on 2026-01-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_alter_adjuntoordentrabajo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
