# Generated by Django 5.2.8 on 2025-11-23 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_movimiento_condicion_pago_movimiento_factura_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Número interno de la orden (podés completarlo luego).', max_length=30)),
                ('fecha_orden', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUTORIZADA', 'Autorizada'), ('FACTURADA', 'Facturada'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('proveedor_nombre', models.CharField(blank=True, help_text='Texto que se imprime en la orden (por si cambiás el proveedor en el maestro).', max_length=200)),
                ('proveedor_cuit', models.CharField(blank=True, max_length=20)),
                ('condicion_pago', models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('30', '30 días'), ('60', '60 días'), ('OTRO', 'Otro plazo')], max_length=20)),
                ('medio_pago_previsto', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro medio')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('factura_tipo', models.CharField(blank=True, choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C'), ('X', 'Factura X / Ticket'), ('OTRO', 'Otro comprobante')], max_length=10)),
                ('factura_numero', models.CharField(blank=True, max_length=50)),
                ('factura_fecha', models.DateField(blank=True, null=True)),
                ('factura_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago', to='finanzas.area')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago', to='finanzas.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de pago',
                'verbose_name_plural': 'Órdenes de pago',
                'ordering': ['-fecha_orden', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='orden_pago',
            field=models.ForeignKey(blank=True, help_text='Si este movimiento proviene de una Orden de pago, se vincula acá.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.ordenpago'),
        ),
        migrations.CreateModel(
            name='OrdenPagoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago_lineas', to='finanzas.area')),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago_lineas', to='finanzas.beneficiario')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago_lineas', to='finanzas.categoria')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='finanzas.ordenpago')),
            ],
            options={
                'verbose_name': 'Línea de orden de pago',
                'verbose_name_plural': 'Líneas de órdenes de pago',
            },
        ),
    ]
