# Generated by Django 4.2.27 on 2026-01-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0007_cuenta_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DNI', 'DNI / Identificación'), ('CUD', 'Certificado Discapacidad'), ('INFORME', 'Informe Social'), ('NOTA', 'Nota / Solicitud'), ('RECIBO', 'Recibo Firmado'), ('OTRO', 'Otro Documento')], default='OTRO', max_length=20)),
                ('archivo', models.FileField(upload_to='legajos_digitales/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, help_text='Breve descripción del archivo', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='finanzas.beneficiario')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Digital',
                'verbose_name_plural': 'Documentos Digitales',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
