# Generated by Django 4.2.27 on 2026-02-06 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0008_documentobeneficiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSensible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFORME_PSI', 'Informe Psicológico'), ('DENUNCIA', 'Denuncia / Judicial'), ('MEDIDA', 'Medida de Protección'), ('SEGUIMIENTO', 'Ficha de Seguimiento'), ('OTRO', 'Otro Reservado')], max_length=20)),
                ('archivo', models.FileField(upload_to='legajos_reservados/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_sensibles', to='finanzas.beneficiario')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Sensible',
                'verbose_name_plural': 'Legajo Reservado',
                'permissions': [('access_legajo_sensible', 'Puede acceder al legajo reservado')],
            },
        ),
    ]
