# Generated by Django 5.2.8 on 2025-11-25 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_ordenpago_movimiento_orden_pago_ordenpagolinea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo', models.CharField(blank=True, help_text="Prefijo opcional para la numeración (ej: 'OC-2025-').", max_length=20)),
                ('siguiente_numero', models.PositiveIntegerField(default=1, help_text='Próximo número correlativo para esta serie.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serie de OC',
                'verbose_name_plural': 'Series de OC',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Número interno de la OC (podés completarlo luego o autogenerar).', max_length=30)),
                ('fecha_oc', models.DateField(help_text='Fecha de emisión de la orden de compra.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUTORIZADA', 'Autorizada'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('rubro_principal', models.CharField(blank=True, choices=[('AS', 'Ayudas sociales'), ('CB', 'Combustible'), ('OB', 'Obras y materiales'), ('SV', 'Servicios contratados'), ('PE', 'Personal / jornales / changas'), ('HI', 'Herramientas / insumos generales'), ('OT', 'Otros')], help_text='Rubro macro de la OC (para filtros rápidos).', max_length=2)),
                ('proveedor_nombre', models.CharField(blank=True, help_text='Texto que se imprime en la OC (por si cambiás el proveedor en el maestro).', max_length=200)),
                ('proveedor_cuit', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='finanzas.area')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='finanzas.proveedor')),
                ('serie', models.ForeignKey(blank=True, help_text='Serie opcional para numeración (puede quedar vacía).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='finanzas.serieoc')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-fecha_oc', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FacturaOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C'), ('X', 'Factura X / Ticket'), ('OTRO', 'Otro comprobante')], max_length=10)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='finanzas.ordencompra')),
            ],
            options={
                'verbose_name': 'Factura de OC',
                'verbose_name_plural': 'Facturas de OC',
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='oc',
            field=models.ForeignKey(blank=True, help_text='Si este movimiento proviene de una Orden de compra, se vincula acá.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.ordencompra'),
        ),
        migrations.CreateModel(
            name='OrdenCompraLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_lineas', to='finanzas.area')),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_lineas', to='finanzas.beneficiario')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_lineas', to='finanzas.categoria')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='finanzas.ordencompra')),
            ],
            options={
                'verbose_name': 'Línea de orden de compra',
                'verbose_name_plural': 'Líneas de órdenes de compra',
            },
        ),
    ]
