# Generated by Django 5.2.8 on 2025-11-26 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_serieoc_ordencompra_facturaoc_movimiento_oc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='numero',
            field=models.CharField(blank=True, help_text='Número interno de la OC. Si lo dejás vacío y usás serie, se puede autogenerar desde la serie. En la impresión se muestra junto con rubro/serie.', max_length=30),
        ),
        migrations.AlterField(
            model_name='serieoc',
            name='prefijo',
            field=models.CharField(blank=True, help_text="Prefijo opcional para la numeración (ej: 'OC-2025-' o 'AS-').", max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField()),
                ('chofer_texto', models.CharField(blank=True, help_text='Nombre del chofer en texto libre (si no está cargado como beneficiario).', max_length=200)),
                ('odometro', models.PositiveIntegerField(blank=True, help_text='Odómetro al momento de la carga (en km).', null=True)),
                ('litros', models.DecimalField(decimal_places=2, help_text='Litros cargados.', max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe total de la carga.', max_digits=14)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por litro. Si lo dejás vacío, se puede calcular a partir de importe/litros.', max_digits=10, null=True)),
                ('tipo_combustible', models.CharField(blank=True, help_text='Nafta super, diesel, etc.', max_length=50)),
                ('estacion', models.CharField(blank=True, help_text='Estación de servicio (YPF, Puma, etc.).', max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_combustible_actualizados', to=settings.AUTH_USER_MODEL)),
                ('chofer', models.ForeignKey(blank=True, help_text='Chofer registrado como beneficiario/empleado (si corresponde).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_combustible_como_chofer', to='finanzas.beneficiario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_combustible_creados', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, help_text='Movimiento contable con el que se pagó esta carga (si ya existe).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_combustible', to='finanzas.movimiento')),
                ('orden_compra', models.ForeignKey(blank=True, help_text='Orden de compra de combustible asociada (si corresponde).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_combustible', to='finanzas.ordencompra')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_combustible', to='finanzas.proveedor')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_combustible', to='finanzas.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de combustible',
                'verbose_name_plural': 'Registros de combustible',
                'ordering': ['-fecha_carga', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParteVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('chofer_texto', models.CharField(blank=True, help_text='Nombre del chofer en texto libre, por si no está dado de alta como beneficiario.', max_length=200)),
                ('odometro_salida', models.PositiveIntegerField(help_text='Odómetro al salir (en km).')),
                ('odometro_regreso', models.PositiveIntegerField(blank=True, help_text='Odómetro al regresar (en km).', null=True)),
                ('nivel_combustible_salida', models.CharField(blank=True, choices=[('0', 'Vacío / casi vacío'), ('1/4', '1/4 tanque'), ('1/2', '1/2 tanque'), ('3/4', '3/4 tanque'), ('LLENO', 'Tanque lleno')], max_length=10)),
                ('nivel_combustible_regreso', models.CharField(blank=True, choices=[('0', 'Vacío / casi vacío'), ('1/4', '1/4 tanque'), ('1/2', '1/2 tanque'), ('3/4', '3/4 tanque'), ('LLENO', 'Tanque lleno')], max_length=10)),
                ('litros_asignados', models.DecimalField(blank=True, decimal_places=2, help_text='Litros que se consideran usados en este viaje (opcional, para cruzar con las cargas).', max_digits=10, null=True)),
                ('recorrido', models.CharField(blank=True, help_text='Descripción breve del recorrido (ej: Tacuarendí – Ocampo – Tacuarendí).', max_length=255)),
                ('tarea', models.CharField(blank=True, help_text='Tarea principal realizada (ej: Recolección residuos, viaje a Santa Fe, etc.).', max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_vehiculo_actualizados', to=settings.AUTH_USER_MODEL)),
                ('chofer', models.ForeignKey(blank=True, help_text='Chofer asignado (si está cargado como beneficiario).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_vehiculo_como_chofer', to='finanzas.beneficiario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_vehiculo_creados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_vehiculo', to='finanzas.vehiculo')),
                ('registro_combustible', models.ForeignKey(blank=True, help_text='Carga de combustible asociada a este parte (si corresponde).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_vehiculo', to='finanzas.registrocombustible')),
            ],
            options={
                'verbose_name': 'Parte de vehículo',
                'verbose_name_plural': 'Partes de vehículo',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
