# Generated by Django 4.2.27 on 2026-02-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_documentosensible'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='persona',
            field=models.ForeignKey(blank=True, help_text='Si esta compra es una ayuda directa para un vecino, seleccionalo aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='finanzas.beneficiario', verbose_name='Beneficiario (Opcional)'),
        ),
    ]
