# Generated by Django 5.2.8 on 2025-11-27 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_alter_ordencompra_numero_alter_serieoc_prefijo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocombustible',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='registrocombustible',
            name='chofer',
        ),
        migrations.RemoveField(
            model_name='registrocombustible',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='registrocombustible',
            name='movimiento',
        ),
        migrations.RemoveField(
            model_name='registrocombustible',
            name='orden_compra',
        ),
        migrations.RemoveField(
            model_name='registrocombustible',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='registrocombustible',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='horometro_referencia',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Horómetro de referencia (si aplica). Opcional.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_referencia',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje de referencia (último servicio / alta). Opcional.', null=True),
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Número interno de OT (ej: OT-0001/2025). Opcional.', max_length=30)),
                ('fecha_ot', models.DateField(help_text='Fecha de la orden de trabajo.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('ENTREGADA', 'Entregada al solicitante'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('tipo_trabajo', models.CharField(choices=[('MECANICA', 'Mecánica / vehículos'), ('ELECTRICA', 'Eléctrica / luminarias'), ('OBRA', 'Obra / albañilería'), ('SERVICIO', 'Servicio a vecino / institución'), ('OTRO', 'Otro')], default='OTRO', help_text='Tipo principal de trabajo realizado.', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('solicitante_texto', models.CharField(blank=True, help_text='Nombre del solicitante (texto libre, para instituciones o casos sin censo).', max_length=200)),
                ('responsable_texto', models.CharField(blank=True, help_text='Texto libre para responsable, por si no está en censo.', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción del trabajo a realizar (pedido inicial).')),
                ('trabajos_realizados', models.TextField(blank=True, help_text='Detalle de trabajos efectivamente realizados (se completa al finalizar).')),
                ('importe_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Importe estimado a cobrar (si aplica).', max_digits=14, null=True)),
                ('importe_final', models.DecimalField(blank=True, decimal_places=2, help_text='Importe final acordado/cobrado (si aplica).', max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, help_text='Área responsable que realiza el trabajo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='finanzas.area')),
                ('categoria_ingreso', models.ForeignKey(blank=True, help_text='Categoría contable para el ingreso (si la OT genera cobro).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_ingreso', to='finanzas.categoria')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_creadas', to=settings.AUTH_USER_MODEL)),
                ('movimiento_ingreso', models.ForeignKey(blank=True, help_text='Movimiento de ingreso generado a partir de esta OT (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='finanzas.movimiento')),
                ('responsable', models.ForeignKey(blank=True, help_text='Responsable principal del trabajo (personal de la comuna).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_responsable', to='finanzas.beneficiario')),
                ('solicitante', models.ForeignKey(blank=True, help_text='Persona solicitante (si está cargada en el censo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_solicitadas', to='finanzas.beneficiario')),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Vehículo utilizado (si corresponde).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='finanzas.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-fecha_ot', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ordenes_trabajo/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_ot_subidos', to=settings.AUTH_USER_MODEL)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='finanzas.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Adjunto de orden de trabajo',
                'verbose_name_plural': 'Adjuntos de órdenes de trabajo',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unidad', models.CharField(blank=True, help_text='Ej: unidad, m, m2, litros, kg, etc.', max_length=50)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario estimado (opcional, para control).', max_digits=14, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, help_text='Costo total (se puede calcular a partir de cantidad x costo unitario).', max_digits=14, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='finanzas.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Material de OT',
                'verbose_name_plural': 'Materiales de OT',
            },
        ),
        migrations.CreateModel(
            name='ViajeVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chofer_nombre', models.CharField(blank=True, help_text='Nombre del chofer / responsable (texto libre, para casos sin censo).', max_length=150)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('fecha_regreso', models.DateField(blank=True, null=True)),
                ('hora_regreso', models.TimeField(blank=True, null=True)),
                ('odometro_inicial', models.PositiveIntegerField(help_text='Lectura de odómetro al momento de la salida (km).')),
                ('odometro_final', models.PositiveIntegerField(blank=True, help_text='Lectura de odómetro al regreso (km).', null=True)),
                ('horometro_inicial', models.DecimalField(blank=True, decimal_places=1, help_text='Horómetro al salir (si aplica, ej: máquinas).', max_digits=10, null=True)),
                ('horometro_final', models.DecimalField(blank=True, decimal_places=1, help_text='Horómetro al regresar (si aplica).', max_digits=10, null=True)),
                ('litros_tanque_inicio', models.DecimalField(blank=True, decimal_places=2, help_text='Litros aproximados en tanque al salir (opcional).', max_digits=8, null=True)),
                ('litros_tanque_fin', models.DecimalField(blank=True, decimal_places=2, help_text='Litros aproximados en tanque al regresar (opcional).', max_digits=8, null=True)),
                ('tipo_recorrido', models.CharField(choices=[('URBANO', 'Urbano / pueblo'), ('RUTA', 'Ruta / viaje largo'), ('COMISION', 'Comisión / trámites'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('origen', models.CharField(help_text='Origen principal del viaje (ej: Tacuarendí - Comuna).', max_length=200)),
                ('destino', models.CharField(help_text='Destino principal del viaje (ej: Reconquista - Banco / AFIP).', max_length=200)),
                ('motivo', models.CharField(blank=True, help_text='Motivo general del viaje (comisión, traslado de personas, compras, etc.).', max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('otros_beneficiarios', models.CharField(blank=True, help_text="Texto libre para familias/grupos no cargados en el censo. Ej: 'Familia Pérez', 'Delegación club X'.", max_length=255)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_actualizados', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, help_text='Área responsable del uso del vehículo en este viaje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_vehiculo', to='finanzas.area')),
                ('beneficiarios', models.ManyToManyField(blank=True, help_text='Personas trasladadas en este viaje (si aplica).', related_name='viajes_trasladado', to='finanzas.beneficiario')),
                ('cargas_combustible', models.ManyToManyField(blank=True, help_text='Movimientos de combustible asociados al viaje. El sistema puede sugerir automáticamente según fecha/vehículo, pero siempre se puede ajustar manualmente.', related_name='viajes_combustible', to='finanzas.movimiento')),
                ('chofer', models.ForeignKey(blank=True, help_text='Chofer o responsable del vehículo (si está cargado en el censo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_como_chofer', to='finanzas.beneficiario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_creados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_vehiculo', to='finanzas.vehiculo')),
            ],
            options={
                'verbose_name': 'Viaje de vehículo',
                'verbose_name_plural': 'Viajes de vehículos',
                'ordering': ['-fecha_salida', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ViajeVehiculoTramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden del tramo dentro del viaje (1, 2, 3, ...).')),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='finanzas.viajevehiculo')),
            ],
            options={
                'verbose_name': 'Tramo de viaje',
                'verbose_name_plural': 'Tramos de viajes',
                'ordering': ['viaje', 'orden'],
            },
        ),
        migrations.DeleteModel(
            name='ParteVehiculo',
        ),
        migrations.DeleteModel(
            name='RegistroCombustible',
        ),
    ]
