# Generated by Django 4.2.27 on 2026-02-20 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0010_ordencompra_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionJuradaDrei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año Fiscal')),
                ('mes', models.IntegerField(choices=[(1, 'Mes 1'), (2, 'Mes 2'), (3, 'Mes 3'), (4, 'Mes 4'), (5, 'Mes 5'), (6, 'Mes 6'), (7, 'Mes 7'), (8, 'Mes 8'), (9, 'Mes 9'), (10, 'Mes 10'), (11, 'Mes 11'), (12, 'Mes 12')], verbose_name='Mes')),
                ('ingresos_declarados', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Ingresos Declarados API')),
                ('alicuota_aplicada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimo_aplicado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('impuesto_determinado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Impuesto a Pagar')),
                ('fecha_presentacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'DDJJ DReI',
                'verbose_name_plural': 'Declaraciones Juradas DReI',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='RubroDrei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Rubro')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Rubro')),
                ('alicuota', models.DecimalField(decimal_places=2, help_text='Porcentaje a aplicar sobre la facturación. Ej: 5.50', max_digits=5, verbose_name='Alícuota (%)')),
                ('importe_minimo', models.DecimalField(decimal_places=2, help_text='Monto mínimo a cobrar si el cálculo por alícuota es menor.', max_digits=14, verbose_name='Importe Mínimo ($)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rubro DReI',
                'verbose_name_plural': 'Rubros DReI',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor / Comercio', 'verbose_name_plural': 'Proveedores y Comercios'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='es_contribuyente_drei',
            field=models.BooleanField(default=False, help_text='Marcar si este proveedor/comercio también tributa Derecho de Registro e Inspección.', verbose_name='Es contribuyente DReI'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='padron_drei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Padrón DReI'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='regimen_simplificado',
            field=models.BooleanField(default=False, verbose_name='Régimen Simplificado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='alias',
            field=models.CharField(blank=True, help_text='Alias bancario para transferencias', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cbu',
            field=models.CharField(blank=True, help_text='CBU/CVU para transferencias', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(help_text='Razón social o Nombre comercial', max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(blank=True, help_text='Rubro principal (Ej: Corralón, Librería)', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='LiquidacionDrei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recargos', models.DecimalField(decimal_places=2, default=0, help_text='Intereses por mora', max_digits=14)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('ddjj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion', to='finanzas.declaracionjuradadrei')),
                ('movimiento_pago', models.OneToOneField(blank=True, help_text='Recibo de caja asociado a este pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidacion_drei', to='finanzas.movimiento')),
            ],
            options={
                'verbose_name': 'Liquidación DReI',
                'verbose_name_plural': 'Liquidaciones DReI',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.AddField(
            model_name='declaracionjuradadrei',
            name='comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddjj_drei', to='finanzas.proveedor'),
        ),
        migrations.AddField(
            model_name='declaracionjuradadrei',
            name='presentada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rubro_drei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comercios', to='finanzas.rubrodrei', verbose_name='Rubro Impositivo DReI'),
        ),
        migrations.AlterUniqueTogether(
            name='declaracionjuradadrei',
            unique_together={('comercio', 'anio', 'mes')},
        ),
    ]
