# Generated by Django 5.2.8 on 2025-12-03 18:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('finanzas', '0011_remove_registrocombustible_actualizado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('AMBOS', 'Ambos')], db_index=True, default='GASTO', help_text='Define si la categoría se usa para INGRESOS, GASTOS o en AMBOS. Las vistas de movimientos pueden filtrar automáticamente por tipo.', max_length=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='APROBADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_operacion',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('TRANSFERENCIA', 'Transferencia')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUTORIZADA', 'Autorizada'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='ordenpago',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUTORIZADA', 'Autorizada'), ('FACTURADA', 'Facturada'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('ENTREGADA', 'Entregada al solicitante'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_nombre', models.CharField(blank=True, help_text='Nombre de la persona atendida (texto libre, si no está en el censo).', max_length=200)),
                ('persona_dni', models.CharField(blank=True, help_text='DNI para casos donde aún no se cargó el censo.', max_length=20)),
                ('persona_barrio', models.CharField(blank=True, help_text='Barrio o paraje de la persona atendida.', max_length=100)),
                ('fecha_atencion', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha en la que se realizó / registró la atención.')),
                ('hora_atencion', models.TimeField(blank=True, help_text='Hora aproximada de la atención (opcional).', null=True)),
                ('motivo_principal', models.CharField(choices=[('CONSULTA', 'Consulta / información'), ('RECLAMO', 'Reclamo'), ('SOLICITUD_AYUDA', 'Solicitud de ayuda'), ('TRAMITE', 'Trámite / gestión administrativa'), ('DENUNCIA', 'Denuncia / situación grave'), ('OTRO', 'Otro')], default='CONSULTA', help_text='Motivo principal que trae la persona.', max_length=20)),
                ('canal', models.CharField(choices=[('PRESENCIAL', 'Presencial en comuna'), ('TELEFONICO', 'Telefónico'), ('WHATSAPP', 'WhatsApp / redes'), ('VISITA_DOMICILIO', 'Visita a domicilio'), ('OTRO', 'Otro canal')], default='PRESENCIAL', help_text='Canal por el cual se tomó la atención.', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', help_text='Prioridad social percibida de la situación.', max_length=10)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de lo que planteó la persona (resumen claro).')),
                ('resultado', models.TextField(blank=True, help_text='Qué se hizo en el momento: orientación, derivación, ayuda concreta, etc.')),
                ('requiere_seguimiento', models.BooleanField(default=False, help_text='Marcá si requiere seguimiento futuro (llamado, visita, gestión).')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('CERRADA', 'Cerrada')], default='CERRADA', help_text='Estado de la atención respecto al seguimiento.', max_length=20)),
                ('origen_interno', models.CharField(blank=True, help_text='Referencia interna: operativo, escuela, institución, barrio, etc.', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, help_text='Área que tomó nota / intervino en la atención.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='finanzas.area')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(blank=True, help_text='Persona atendida (si está cargada en el censo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='finanzas.beneficiario')),
                ('tarea_seguimiento', models.ForeignKey(blank=True, help_text='Tarea en Agenda vinculada para el seguimiento (si existe).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='agenda.tarea')),
            ],
            options={
                'verbose_name': 'Atención a persona',
                'verbose_name_plural': 'Atenciones a personas',
                'ordering': ['-fecha_atencion', '-id'],
                'permissions': [('ver_panel_atenciones', 'Puede ver el panel resumido de atenciones sociales')],
                'indexes': [models.Index(fields=['fecha_atencion', 'estado'], name='finanzas_at_fecha_a_61fff3_idx'), models.Index(fields=['persona_dni'], name='finanzas_at_persona_a1f636_idx')],
            },
        ),
    ]
