# Generated by Django 4.2.27 on 2026-02-21 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_declaracionjuradadrei_rubrodrei_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubrodrei',
            options={'ordering': ['codigo'], 'verbose_name': 'Rubro DReI', 'verbose_name_plural': 'Rubros DReI (Anexo I)'},
        ),
        migrations.AlterUniqueTogether(
            name='declaracionjuradadrei',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rubrodrei',
            name='importe_minimo',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tasa_diferencial',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Solo si este comercio tiene una alícuota especial pactada.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rubrodrei',
            name='minimo_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo si la venta es baja o nula.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='declaracionjuradadrei',
            name='anio',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='declaracionjuradadrei',
            name='impuesto_determinado',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='declaracionjuradadrei',
            name='ingresos_declarados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos Brutos Declarados'),
        ),
        migrations.AlterField(
            model_name='declaracionjuradadrei',
            name='mes',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')]),
        ),
        migrations.AlterField(
            model_name='declaracionjuradadrei',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Aclaraciones o notas'),
        ),
        migrations.AlterField(
            model_name='liquidaciondrei',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='liquidaciondrei',
            name='monto_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cbu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='es_contribuyente_drei',
            field=models.BooleanField(default=False, verbose_name='Es contribuyente DReI'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='regimen_simplificado',
            field=models.BooleanField(default=False, help_text='Marcar si paga monto fijo mensual (Monotributo local)', verbose_name='Régimen Simplificado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(blank=True, help_text='Rubro comercial general', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rubrodrei',
            name='alicuota',
            field=models.DecimalField(decimal_places=5, help_text='Ej: 0.005 para 0.5%', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rubrodrei',
            name='codigo',
            field=models.CharField(help_text='Código según Ordenanza (ej: 101)', max_length=10),
        ),
        migrations.AlterField(
            model_name='rubrodrei',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='declaracionjuradadrei',
            unique_together={('comercio', 'mes', 'anio')},
        ),
        migrations.RemoveField(
            model_name='declaracionjuradadrei',
            name='alicuota_aplicada',
        ),
        migrations.RemoveField(
            model_name='declaracionjuradadrei',
            name='minimo_aplicado',
        ),
    ]
