# Generated by Django 4.2.27 on 2026-02-21 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_alter_rubrodrei_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='regimen_simplificado',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='rubro_drei',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='tasa_diferencial',
        ),
        migrations.AddField(
            model_name='declaracionjuradadrei',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.rubrodrei', verbose_name='Actividad Declarada (Nomenclador)'),
        ),
        migrations.AddField(
            model_name='declaracionjuradadrei',
            name='alicuota_manual',
            field=models.DecimalField(decimal_places=5, default=0.005, help_text='Ej: Escriba 0.005 para 0.5%. El sistema la tomará para el cálculo final.', max_digits=6, verbose_name='Alícuota Aplicada (%)'),
        ),
        migrations.AlterField(
            model_name='declaracionjuradadrei',
            name='ingresos_declarados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Facturación Mensual'),
        ),
        migrations.AlterField(
            model_name='liquidaciondrei',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='es_contribuyente_drei',
            field=models.BooleanField(default=False, help_text='Marcar para que aparezca en el sistema de recaudación comunal.', verbose_name='Activo en Padrón DReI'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(blank=True, help_text='Rubro comercial general libre (Ej: Ferretería)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rubrodrei',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
