# Generated by Django 4.2.27 on 2026-01-28 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, help_text='Código interno o de barra', max_length=50, null=True)),
                ('unidad', models.CharField(choices=[('UNIDAD', 'Unidad'), ('KG', 'Kilogramos'), ('LT', 'Litros'), ('MTS', 'Metros'), ('BOLSA', 'Bolsa'), ('CAJA', 'Caja')], default='UNIDAD', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5, help_text='Alerta cuando baje de esto', max_digits=10)),
                ('es_herramienta', models.BooleanField(default=False, help_text='Si se marca, se espera devolución.', verbose_name='¿Es Herramienta/Activo?')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='inventario.categoriainsumo')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', '🟢 Entrada / Compra'), ('SALIDA', '🔴 Salida / Consumo'), ('PRESTAMO', '🟠 Préstamo (Herramienta)'), ('DEVOLUCION', '🔵 Devolución (Herramienta)'), ('AJUSTE', '⚖️ Ajuste Inventario (Corrección)')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('destinatario', models.CharField(blank=True, help_text='Quién retira o a qué obra va (Ej: Juan Perez, Plaza Central)', max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.insumo')),
                ('usuario', models.ForeignKey(help_text='Quién registró el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
