# Generated by Django 4.2.27 on 2026-02-02 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0008_documentobeneficiario'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientostock',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='referencia',
            field=models.CharField(blank=True, help_text="Ej: 'Préstamo a Juan Perez' o 'Compra OC-005'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='es_herramienta',
            field=models.BooleanField(default=False, help_text='Si se marca, habilita el sistema de Préstamos/Pañol.', verbose_name='¿Es Herramienta/Activo?'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', '🟢 Entrada / Compra'), ('SALIDA', '🔴 Salida / Consumo'), ('PRESTAMO', '🟠 Salida por Préstamo'), ('DEVOLUCION', '🔵 Reingreso por Devolución'), ('AJUSTE', '⚖️ Ajuste Inventario')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', '🟠 Pendiente de Devolución'), ('DEVUELTO', '✅ Devuelto / Cerrado'), ('PERDIDO', '❌ Perdido / No Devuelto')], default='PENDIENTE', max_length=20)),
                ('observaciones_salida', models.TextField(blank=True, help_text='Estado al salir (ej: Nueva, Usada)', null=True)),
                ('observaciones_devolucion', models.TextField(blank=True, help_text='Estado al volver (ej: Rota, Ok)', null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(limit_choices_to={'es_herramienta': True}, on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='herramientas_prestadas', to='finanzas.beneficiario', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Préstamo de Herramienta',
                'verbose_name_plural': 'Pañol / Préstamos',
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
