# Generated by Django 4.2.27 on 2026-01-21 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('PAGO_VENCIMIENTO', 'Pago / vencimiento'), ('DOCUMENTACION', 'Documentación'), ('REUNION_EVENTO', 'Reunión / evento'), ('GESTION_ADMIN', 'Gestión administrativa'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('SISTEMA', 'Sistema')], default='MANUAL', max_length=10)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_recordatorio', models.DateField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('ambito', models.CharField(choices=[('FINANZAS', 'Finanzas'), ('SOCIAL', 'Social'), ('GENERAL', 'General')], default='GENERAL', max_length=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea / Pendiente',
                'verbose_name_plural': 'Tareas / Pendientes',
                'ordering': ['fecha_vencimiento', '-prioridad', '-id'],
            },
        ),
    ]
