# Generated by Django 4.2.27 on 2026-01-21 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='finanzas.movimiento'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='orden_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='finanzas.ordenpago'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='finanzas.beneficiario'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='finanzas.proveedor'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['estado'], name='agenda_tare_estado_92a56e_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['fecha_vencimiento'], name='agenda_tare_fecha_v_17cb89_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['responsable'], name='agenda_tare_respons_865497_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['ambito'], name='agenda_tare_ambito_8c6fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['tipo'], name='agenda_tare_tipo_086977_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['prioridad'], name='agenda_tare_priorid_6ee4ea_idx'),
        ),
    ]
