# Generated by Django 4.2.27 on 2026-01-25 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_ordencompra_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General / Trámite'), ('SOCIAL', 'Acción Social'), ('OBRAS', 'Reclamo Obras/Servicios')], default='GENERAL', max_length=20)),
                ('nombre_temporal', models.CharField(blank=True, max_length=150)),
                ('motivo', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['-fecha_atencion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('chofer', models.CharField(blank=True, max_length=100)),
                ('destino', models.CharField(blank=True, max_length=200)),
                ('km_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('km_regreso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('km_recorridos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('combustible_litros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hoja de Ruta',
                'verbose_name_plural': 'Hojas de Ruta',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['fecha_vencimiento', '-prioridad', '-id'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.RemoveIndex(
            model_name='tarea',
            name='agenda_tare_estado_92a56e_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarea',
            name='agenda_tare_fecha_v_17cb89_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarea',
            name='agenda_tare_respons_865497_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarea',
            name='agenda_tare_ambito_8c6fa8_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarea',
            name='agenda_tare_tipo_086977_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarea',
            name='agenda_tare_priorid_6ee4ea_idx',
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hojas_ruta_creadas_agenda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas_ruta_agenda', to='finanzas.vehiculo'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atencion',
            name='derivado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_derivadas_agenda', to='finanzas.area'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_agenda', to='finanzas.beneficiario'),
        ),
    ]
